language: node_js
node_js:
  - "4.0"
  - "iojs"
  - "iojs-v2"
  - "iojs-v1"
  - "0.12"
  - "0.10"
  - "0.8"
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libexiv2-dev
before_install:
  - export CXX=g++-4.8
  - case ${TRAVIS_NODE_VERSION} in
        iojs*)
            echo "Not upgrading npm for iojs."
            ;;
        *)
            npm update -g npm@2.6.1
            ;;
    esac
